
package com.agh.edu.soap_client_simulator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapServices", targetNamespace = "http://soap.edu.agh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapServices {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editElement", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.EditElement")
    @ResponseWrapper(localName = "editElementResponse", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.EditElementResponse")
    public void editElement(
        @WebParam(name = "arg0", targetNamespace = "")
        ElementDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewCategoryType", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.AddNewCategoryType")
    @ResponseWrapper(localName = "addNewCategoryTypeResponse", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.AddNewCategoryTypeResponse")
    public void addNewCategoryType(
        @WebParam(name = "arg0", targetNamespace = "")
        CategoryTypeDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewElementType", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.AddNewElementType")
    @ResponseWrapper(localName = "addNewElementTypeResponse", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.AddNewElementTypeResponse")
    public void addNewElementType(
        @WebParam(name = "arg0", targetNamespace = "")
        ElementTypeDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.agh.edu.soap_client_simulator.ElementDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getElementDtoById", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.GetElementDtoById")
    @ResponseWrapper(localName = "getElementDtoByIdResponse", targetNamespace = "http://soap.edu.agh.com/", className = "com.agh.edu.soap_client_simulator.GetElementDtoByIdResponse")
    public ElementDto getElementDtoById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
